server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE         #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/**         # 断言，路径相匹配的进行路由
            - After=2022-06-28T10:32:27.712+08:00[Asia/Shanghai]
            - Cookie=id,3[1-3]
            - Before=2022-06-28T11:59:27.712+08:00[Asia/Shanghai]
            - Header=X-Request-Id, \d+
            - Host=eureka**.com
            - Method=GET
            - Query=id,31

        - id: payment_routh2 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://CLOUD-PAYMENT-SERVICE          #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/sleep/**         # 断言，路径相匹配的进行路由

        - id: payment_routh3 #payment_route    #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: http://news.baidu.com:80          #匹配后提供服务的路由地址
          predicates:
            - Path=/guonei         # 断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: cloud-gateway-service
  client: #服务提供者provider注册进eureka服务列表内
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka



